Repository LearnWeb3DAO/Junior-Track, pull requests merged in 2023-02, with the labels that each got.

#18 Ceramic selfID: Update ID format
  Ceramic-SelfID.md
Labels: bug, documentation

#22 fixed the typo error
  Layer-2-Blockchains.md
Labels: documentation, good first issue

#23 fixed the typo error
  Radicle.md
Labels: documentation

#24 fixed the typo errors
  Lottery-Game-Chainlink-VRF.md
Labels: documentation

#25 fixed the typo errors
  Indexing-Contract-Data-TheGraph.md
Labels: documentation
